services:
  docker-nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8111:80"
    volumes:
      - ./app/frontend:/var/www
      - ./app/backend:/var/app/backend
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web-network
    depends_on:
      - docker-php-fpm

  docker-php-fpm:
    restart: always
    env_file:
        - .env
    build: 
      context: ./php-fpm
    volumes:
      - ./app/frontend:/var/www
      - ./app/backend:/var/app/backend
      - ./seeders:/var/app/seeders
      - ./.env:/var/app/.env
      - .:/var/app/project
    working_dir: /var/app/project
    networks:
      - web-network

# define the network
networks:
  web-network:
volumes:
  PG_data: